# Generated by Django 5.1 on 2024-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assignment_delete_date_delete_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.IntegerField(default=24),
        ),
    ]
