# Generated by Django 5.1 on 2024-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignment_date_assignment_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='year',
        ),
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.CharField(default='None', max_length=69),
        ),
    ]
