# Generated by Django 4.2.14 on 2024-08-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_assignment_day_remove_assignment_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('None', 'None'), ('Chi', 'Chi'), ('Eng', 'Eng'), ('Math', 'Math'), ('Phy', 'Phy'), ('Chem', 'Chem'), ('Bio', 'Bio'), ('PTH', 'PTH'), ('ICT', 'ICT'), ('L&S', 'L&S'), ('Econ', 'Econ'), ('Geog', 'Geog'), ('C Hist', 'C Hist'), ('Hist', 'Hist'), ('Music', 'Music'), ('BAFS', 'BAFS'), ('VA', 'VA'), ('PE', 'PE'), ('RE', 'RE')], default='None', max_length=10),
        ),
    ]
